#!/usr/bin/env sh

PATHTOLIGHT=/sys/class/backlight/intel_backlight
brightness=`cat $PATHTOLIGHT/brightness`
max=`cat $PATHTOLIGHT/max_brightness`

numofulevels=100
incrusize=$(( $max/$numofulevels ))
cur_ulevel=$(( $brightness/$incrusize ))

color9="#FFFFFF"
color8="#EEEEEE"
color7="#DDDDDD"
color6="#CCCCCC"
color5="#BBBBBB"
color4="#AAAAAA"
color3="#999999"
color2="#888888"
color1="#777777"
color0="#666666"

brilev=$(( $cur_ulevel/10 ))
case $brilev in
	0) color=$color0 ;;
	1) color=$color1 ;;
	2) color=$color2 ;;
	3) color=$color3 ;;
	4) color=$color4 ;;
	5) color=$color5 ;;
	6) color=$color6 ;;
	7) color=$color7 ;;
	8) color=$color8 ;;
	9) color=$color9 ;;
	*) color=$color9 ;;
esac
bri=$brightness
echo "<span color=\"$color\">|$cur_ulevel%</span>"

case $BLOCK_BUTTON in
	4) backlight u & break ;;
	5) backlight d & break ;;
	8) backlight u & break ;;
	9) backlight d & break ;;
esac 
