#!/usr/bin/env bash

battery="acpi -i"
no=`$battery | grep capacity | awk '{for(i=1;i<=NF;i++)if($i=="Battery")print $(i+1)}' | sed 's/://'`
batinfo=`$battery | grep "Battery $no" | grep -v capacity`

batinfo=`echo ${batinfo#*: }`
status=`echo $batinfo | cut -f1 -d","`
status=`echo "$status" | awk '{print tolower($0)}'`

batinfo=`echo ${batinfo#*, }`
capacity=`echo $batinfo | cut -f1 -d"," | sed 's/\%//'`


batinfo=`echo ${batinfo#*, }`
hour=`echo $batinfo | awk '{print $1}' | sed 's/\:/ /g' | awk '{print $1}' | sed 's/^0*//'`
min=`echo $batinfo | awk '{print $1}' | sed 's/\:/ /g' | awk '{print $2}' | sed 's/^0*//'`

if [ -z $hour ] ; then
	shour=""
	if [ -z $min ] ; then
		smin=""
	else
		smin=$min"m"
	fi
else
	shour=$hour"h"
	if [ -z $min ] ; then
		smin=""
	else
		shour="$shour "
		smin=$min"m"
	fi
fi

remaining=" ($shour$smin)"
if [ $remaining = "(rateh)" ] ; then
  remaining=""
fi

white="#FFFFFF"
green="#00BB00"	
orange="#BA5000"	
red="#BB0000"	
yellow="#FDDC00"

color=$white

if [ $capacity -ge 75 ]; then
	color=$green
elif [ $capacity -ge 40 ]; then
	color=$white
elif [ $capacity -ge 25 ]; then
	color=$yellow
elif [ $capacity -ge 10 ]; then
	color=$orange
else
	color=$red
fi

[ "$status" = "charging" ] && color=$white
if [ "$status" = "full" ] || [ "$status" = "unknown" ] || [ -z $status ] || [ $capacity -ne $capacity ] ;then
        remaining=""
fi

case $status in
	charging) cond="" ;;
	"not charging") cond="" ;;
	full) cond="" ;;
	unknown) cond="" ;;
	discharging) 
		if [ $capacity -ge 85 ] ; then
                	cond=""
        	elif [ $capacity -ge 60 ] ; then
                	cond=""
        	elif [ $capacity -ge 40 ] ; then
                	cond=""
        	elif [ $capacity -ge 15 ] ; then
                	cond=""
        	elif  [ $capacity -ge 0 ] ; then
                	cond=""
        	else
                	cond="❗Unknown capacity, check acpi"
        	fi
		;;
	*) cond="❗Unidentified battery status, check acpi" ;;
esac

echo "$cond <span color=\"${color}\">${capacity}%</span>${remaining}"
