#!/usr/bin/env sh

capacity=$(cat /sys/class/power_supply/BAT0/capacity) || exit
status=$(cat /sys/class/power_supply/BAT0/status)

battery=`acpi`

hour=`echo $battery | awk '{print $5}' | sed 's/\:/ /g' | awk '{print $1}' | sed 's/^0*//'`
min=`echo $battery | awk '{print $5}' | sed 's/\:/ /g' | awk '{print $2}' | sed 's/^0*//'`

if [ -z $hour ] ; then
	shour=""
else
	shour=$hour"h "
fi
if [ -z $min ] ; then
	smin=""
else
	smin=$min"m"
fi

remaining=" ($shour$smin)"

white="#FFFFFF"
green="#00BB00"	
orange="#BA5000"	
red="#BB0000"	
yellow="#FDDC00"

color=$white

if [ $capacity -ge 75 ]; then
	color=$green
elif [ $capacity -ge 40 ]; then
	color=$white
elif [ $capacity -ge 25 ]; then
	color=$yellow
elif [ $capacity -ge 10 ]; then
	color=$orange
else
	color=$red
	warn=""
fi

[ -z $warn ] && warn=" "

[ "$status" = "Charging" ] && color=$white

[ "$status" = "Full" ] && remaining=""

cond="$(echo "$status" | sed -e "s/,//;s/Discharging/🔋/;s/Not Charging//;s/Charging//;s/Unknown//;s/Full//;s/ 0*/ /g;s/ :/ /g")"

if [ $cond = "🔋" ] ; then
	if [ $capacity -ge 85 ] ; then
		cond=""
	elif [ $capacity -ge 60 ] ; then
                cond=""
	elif [ $capacity -ge 40 ] ; then
                cond=""
	elif [ $capacity -ge 15 ] ; then
                cond=""
	elif  [ $capacity -ge 0 ] ; then
                cond=""
	else
		cond="❗"
	fi
fi


echo "$cond <span color=\"${color}\">${capacity}%</span>${remaining}"

