#!/usr/bin/env sh

date '+%a, %Y/%m/%d %H:%M:%S '


case $BLOCK_BUTTON in
	1) setsid break & gnome-calendar & break ;;
	2) setsid break & gnome-calendar & break ;;
	3) setsid break & gnome-calendar & break ;;
esac
