#!/bin/bash

#Resolutions
PC_r="3840x2160"
HomeDELL1610_r="1920x1200"
HomeDELL169_r="1920x1080"
OfficeDELL169_r="1680x1050"

home="
PCpos:0x2400
PCvar:primary
PCvar:preferred
HomeDELL1610pos:0x0
HomeDELL1610scale:2x2
HomeDELL169pos:3840x240
HomeDELL169scale:2x2
"

echo $home 



#home2


#office


#officeV

